/*
 * SplashScreenJDialog.java
 *
 * Created on July 14, 2007, 3:31 PM
 */

package jm.org.bsj.labelprint.ui;

import javax.swing.JOptionPane;
import jm.org.bsj.labelprint.SystemOptions;

/**
 *
 * @author  Desmond Bennett
 */
public class SplashScreenJDialog extends javax.swing.JDialog implements Runnable {
    private LabelPrintFrame labelPrintFrame;
    private boolean bSetupSuccessful;
    private SystemOptions sysOptions;
    
    /** Creates new form SplashScreenJDialog */
    public SplashScreenJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        labelPrintFrame = (LabelPrintFrame)parent;
        sysOptions = labelPrintFrame.getSystemOptions();
        
        // Centre
        this.setLocationRelativeTo(null);
        new Thread(this).start();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("");
        setBackground(new java.awt.Color(204, 204, 255));
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);
        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Initializing database connection. Please wait...");
        jPanel1.add(jLabel1);

        jProgressBar1.setValue(10);
        jPanel1.add(jProgressBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreenJDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    public void run() {
        
        // Setup persistence/connect to database
        // Display error message only if option to store database set
        if (!labelPrintFrame.setupDatabaseConnection() && sysOptions.isConnectToDatabase()) {
            JOptionPane.showMessageDialog(this,
                    "A database connection error occurred.\n" +
                    "Consult your database administrator",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
            
        }
        jProgressBar1.setValue(50);        
        // Setup font mapper for pdf exportation
        jLabel1.setText("Initializing fonts. Please wait...");
        if (!labelPrintFrame.setupFontDefaultFontMapper()) {
            JOptionPane.showMessageDialog(this,
                    "A font initialization error occurred.\n" +
                    "Consult your system administrator",
                    "Font Initialization Error",
                    JOptionPane.ERROR_MESSAGE);
            
        }
        jProgressBar1.setValue(100);
        dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    
}
