/*
LabelPrint - A general purpose energy label printing application 
Copyright (C) 2018  D P Bennett & Associates Limited

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

Email: info@dpbennett.com.jm
 */
package jm.com.dpbennett.labelprint.ui;

import java.awt.Graphics;

/**
 *
 * @author dbennett
 */
public class LabelDataPanel extends javax.swing.JPanel {

    private LabelPrintFrame labelPrintFrame;
    private Boolean isLoading;

    /**
     * Creates new form LabelDataDialog
     */
    public LabelDataPanel() {
        initComponents();
    }

    /**
     * Creates new form LabelDataDialog
     *
     * @param labelPrintFrame
     */
    public LabelDataPanel(LabelPrintFrame labelPrintFrame) {
        this.labelPrintFrame = labelPrintFrame;
        initComponents();
    }

    /**
     * Get label data from dialog
     */
    public void getLabelData() {

        labelPrintFrame.getEnergyLabel().setDistributor(jDistributor.getText());
        labelPrintFrame.getEnergyLabel().setDefrost(jDefrost.getText());
        labelPrintFrame.getEnergyLabel().setCostPerKwh(jElectricityRate.getText());
        labelPrintFrame.getEnergyLabel().setBrand(jBrand.getText());
        labelPrintFrame.getEnergyLabel().setModel(jModelNo.getText());
        labelPrintFrame.getEnergyLabel().setValidity(jValidity.getText());
        labelPrintFrame.getEnergyLabel().setCapacity(jCapacity.getText());
        labelPrintFrame.getEnergyLabel().setStandard(jStandardNo.getText());
        labelPrintFrame.getEnergyLabel().setOperatingCost(jOperatingCost.getText());
        labelPrintFrame.getEnergyLabel().setManufacturer(jManufacturer.getText());
        labelPrintFrame.getEnergyLabel().setCountry(jCountryOfOrigin.getText());
        labelPrintFrame.getEnergyLabel().setAnnualConsumption(jAnnualConsumption.getText());
        labelPrintFrame.getEnergyLabel().setType(jProductType.getSelectedItem().toString());
        labelPrintFrame.getEnergyLabel().setJobNumber(jJobNumber.getText());
        labelPrintFrame.getEnergyLabel().setLabelName(jLabelName.getText());

    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        loadLabelData();
    }

    private void loadLabelData() {
        isLoading = true;
        jDistributor.setText(labelPrintFrame.getEnergyLabel().getDistributor());
        jDefrost.setText(labelPrintFrame.getEnergyLabel().getDefrost());
        jElectricityRate.setText(labelPrintFrame.getEnergyLabel().getCostPerKwh());
        jBrand.setText(labelPrintFrame.getEnergyLabel().getBrand());
        jModelNo.setText(labelPrintFrame.getEnergyLabel().getModel());
        jValidity.setText(labelPrintFrame.getEnergyLabel().getValidity());
        jCapacity.setText(labelPrintFrame.getEnergyLabel().getCapacity());
        jStandardNo.setText(labelPrintFrame.getEnergyLabel().getStandard());
        jOperatingCost.setText(labelPrintFrame.getEnergyLabel().getOperatingCost());
        jManufacturer.setText(labelPrintFrame.getEnergyLabel().getManufacturer());
        jCountryOfOrigin.setText(labelPrintFrame.getEnergyLabel().getCountry());
        jAnnualConsumption.setText(labelPrintFrame.getEnergyLabel().getAnnualConsumption());
        jProductType.setSelectedItem(labelPrintFrame.getEnergyLabel().getType());
        jJobNumber.setText(labelPrintFrame.getEnergyLabel().getJobNumber());
        jLabelName.setText(labelPrintFrame.getEnergyLabel().getLabelName());
        isLoading = false;        
    }
    
    public void updateLabelData() {
        loadLabelData();
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jJobNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jProductType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jCapacity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDefrost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDistributor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jManufacturer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBrand = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jModelNo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCountryOfOrigin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jOperatingCost = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jAnnualConsumption = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jElectricityRate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jValidity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jStandardNo = new javax.swing.JTextField();
        jViewLabel = new javax.swing.JButton();
        jSaveLabel = new javax.swing.JButton();

        setName(""); // NOI18N
        setLayout(new java.awt.GridLayout(16, 2, 2, 5));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setLabelFor(jProductType);
        jLabel14.setText("Label Name:");
        add(jLabel14);

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jLabelNameCaretUpdate(evt);
            }
        });
        add(jLabelName);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setLabelFor(jJobNumber);
        jLabel15.setText("Job Number:");
        add(jLabel15);

        jJobNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jJobNumber.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jJobNumberCaretUpdate(evt);
            }
        });
        add(jJobNumber);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setLabelFor(jProductType);
        jLabel1.setText("Product Type:");
        add(jLabel1);

        jProductType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic Refrigerator", "Freezer", "Refrigerator", "Room Air-conditioner", " " }));
        jProductType.setSelectedIndex(2);
        jProductType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductTypeActionPerformed(evt);
            }
        });
        add(jProductType);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Capacity (cu. m):");
        add(jLabel2);

        jCapacity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCapacity.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jCapacityCaretUpdate(evt);
            }
        });
        add(jCapacity);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Defrost (Manual/Automatic):");
        add(jLabel3);

        jDefrost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jDefrost.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jDefrostCaretUpdate(evt);
            }
        });
        add(jDefrost);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Distributor:");
        add(jLabel4);

        jDistributor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jDistributor.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jDistributorCaretUpdate(evt);
            }
        });
        add(jDistributor);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Manufacturer:");
        add(jLabel5);

        jManufacturer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jManufacturer.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jManufacturerCaretUpdate(evt);
            }
        });
        add(jManufacturer);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Brand:");
        add(jLabel6);

        jBrand.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBrand.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jBrandCaretUpdate(evt);
            }
        });
        add(jBrand);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Model No.:");
        add(jLabel7);

        jModelNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jModelNo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jModelNoCaretUpdate(evt);
            }
        });
        add(jModelNo);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Country of Origin:");
        add(jLabel8);

        jCountryOfOrigin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCountryOfOrigin.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jCountryOfOriginCaretUpdate(evt);
            }
        });
        add(jCountryOfOrigin);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Operating Cost ($/yr):");
        add(jLabel9);

        jOperatingCost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jOperatingCost.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jOperatingCostCaretUpdate(evt);
            }
        });
        add(jOperatingCost);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Anual Consumption (kwh/yr):");
        add(jLabel10);

        jAnnualConsumption.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jAnnualConsumption.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jAnnualConsumptionCaretUpdate(evt);
            }
        });
        add(jAnnualConsumption);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Electricity Rate ($/kwh):");
        add(jLabel11);

        jElectricityRate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jElectricityRate.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jElectricityRateCaretUpdate(evt);
            }
        });
        add(jElectricityRate);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Validity (year):");
        add(jLabel12);

        jValidity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jValidity.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jValidityCaretUpdate(evt);
            }
        });
        add(jValidity);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Standard No.:");
        add(jLabel13);

        jStandardNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jStandardNo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jStandardNoCaretUpdate(evt);
            }
        });
        add(jStandardNo);

        jViewLabel.setText("View");
        jViewLabel.setToolTipText("View label with current data");
        jViewLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewLabelActionPerformed(evt);
            }
        });
        add(jViewLabel);

        jSaveLabel.setText("Save");
        jSaveLabel.setToolTipText("Save the label data");
        jSaveLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveLabelActionPerformed(evt);
            }
        });
        add(jSaveLabel);
    }// </editor-fold>//GEN-END:initComponents


    private void jSaveLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveLabelActionPerformed
        // tk
        System.out.println("Impl label save...use labelprintframe class and business-entity method for saving entities");
        //restoreRefrigeratorData();
        //labelPrintFrame.setFileDirty(false);
        // Set label view panel
        //labelPrintFrame.getTabbedPane().setSelectedIndex(1);
    }//GEN-LAST:event_jSaveLabelActionPerformed

    private void jStandardNoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jStandardNoCaretUpdate
        if (!isLoading) {
            if (!jStandardNo.getText().trim().equals(labelPrintFrame.getEnergyLabel().getStandard().trim())) {
                labelPrintFrame.getEnergyLabel().setStandard(jStandardNo.getText().trim());
                labelPrintFrame.setDirty(true);
            }
        }
    }//GEN-LAST:event_jStandardNoCaretUpdate

    private void jElectricityRateCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jElectricityRateCaretUpdate
        if (!isLoading) {
            if (!jElectricityRate.getText().trim().equals(labelPrintFrame.getEnergyLabel().getCostPerKwh().trim())) {
                labelPrintFrame.getEnergyLabel().setCostPerKwh(jElectricityRate.getText().trim());
                labelPrintFrame.setDirty(true);
            }
        }
    }//GEN-LAST:event_jElectricityRateCaretUpdate

    private void jAnnualConsumptionCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jAnnualConsumptionCaretUpdate
        if (!isLoading) {
            if (!jAnnualConsumption.getText().trim().equals(labelPrintFrame.getEnergyLabel().getAnnualConsumption().trim())) {
                labelPrintFrame.getEnergyLabel().setAnnualConsumption(jAnnualConsumption.getText().trim());
                labelPrintFrame.setDirty(true);
            }
        }
    }//GEN-LAST:event_jAnnualConsumptionCaretUpdate

    private void jOperatingCostCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jOperatingCostCaretUpdate
        if (!isLoading) {
            if (!jOperatingCost.getText().trim().equals(labelPrintFrame.getEnergyLabel().getOperatingCost().trim())) {
                labelPrintFrame.getEnergyLabel().setOperatingCost(jOperatingCost.getText().trim());
                labelPrintFrame.setDirty(true);
            }
        }
    }//GEN-LAST:event_jOperatingCostCaretUpdate

    private void jCountryOfOriginCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jCountryOfOriginCaretUpdate
        if (!isLoading) {
            if (!jCountryOfOrigin.getText().trim().equals(labelPrintFrame.getEnergyLabel().getCountry().trim())) {
                labelPrintFrame.getEnergyLabel().setCountry(jCountryOfOrigin.getText().trim());
                labelPrintFrame.setDirty(true);
            }
        }
    }//GEN-LAST:event_jCountryOfOriginCaretUpdate

    private void jModelNoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jModelNoCaretUpdate
        if (!isLoading) {
            if (!jModelNo.getText().trim().equals(labelPrintFrame.getEnergyLabel().getModel().trim())) {
                labelPrintFrame.getEnergyLabel().setModel(jModelNo.getText().trim());
                labelPrintFrame.setDirty(true);
            }
        }
    }//GEN-LAST:event_jModelNoCaretUpdate

    private void jBrandCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jBrandCaretUpdate
        if (!isLoading) {
            if (!jBrand.getText().trim().equals(labelPrintFrame.getEnergyLabel().getBrand().trim())) {
                labelPrintFrame.getEnergyLabel().setBrand(jBrand.getText().trim());
                labelPrintFrame.setDirty(true);
            }
        }
    }//GEN-LAST:event_jBrandCaretUpdate

    private void jManufacturerCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jManufacturerCaretUpdate
        if (!isLoading) {
            if (!jManufacturer.getText().trim().equals(labelPrintFrame.getEnergyLabel().getManufacturer().trim())) {
                labelPrintFrame.getEnergyLabel().setManufacturer(jManufacturer.getText().trim());
                labelPrintFrame.setDirty(true);
            }
        }
    }//GEN-LAST:event_jManufacturerCaretUpdate

    private void jDistributorCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jDistributorCaretUpdate
        if (!isLoading) {
            if (!jDistributor.getText().trim().equals(labelPrintFrame.getEnergyLabel().getDistributor().trim())) {
                labelPrintFrame.getEnergyLabel().setDistributor(jDistributor.getText().trim());
                labelPrintFrame.setDirty(true);
            }
        }
    }//GEN-LAST:event_jDistributorCaretUpdate

    private void jDefrostCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jDefrostCaretUpdate
        if (!isLoading) {
            if (!jDefrost.getText().trim().equals(labelPrintFrame.getEnergyLabel().getDefrost().trim())) {
                labelPrintFrame.getEnergyLabel().setDefrost(jDefrost.getText().trim());
                labelPrintFrame.setDirty(true);
            }
        }
    }//GEN-LAST:event_jDefrostCaretUpdate

    private void jCapacityCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jCapacityCaretUpdate
        if (!isLoading) {
            if (!jCapacity.getText().trim().equals(labelPrintFrame.getEnergyLabel().getCapacity().trim())) {
                labelPrintFrame.getEnergyLabel().setCapacity(jCapacity.getText().trim());
                labelPrintFrame.setDirty(true);
            }
        }
    }//GEN-LAST:event_jCapacityCaretUpdate

    private void jValidityCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jValidityCaretUpdate
        if (!isLoading) {
            if (!jValidity.getText().trim().equals(labelPrintFrame.getEnergyLabel().getValidity().trim())) {
                labelPrintFrame.getEnergyLabel().setValidity(jValidity.getText().trim());
                labelPrintFrame.setDirty(true);
            }
        }
    }//GEN-LAST:event_jValidityCaretUpdate

    private void jViewLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewLabelActionPerformed
        // Update label and set label view panel     
        labelPrintFrame.getLabelPanel().updateLabel();
        labelPrintFrame.getTabbedPane().setSelectedIndex(1);
    }//GEN-LAST:event_jViewLabelActionPerformed

    private void jLabelNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jLabelNameCaretUpdate
        if (!isLoading) {
            if (!jLabelName.getText().trim().equals(labelPrintFrame.getEnergyLabel().getLabelName().trim())) {
                labelPrintFrame.getEnergyLabel().setLabelName(jLabelName.getText().trim());
                labelPrintFrame.setDirty(true);
            }
        }
    }//GEN-LAST:event_jLabelNameCaretUpdate

    private void jJobNumberCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jJobNumberCaretUpdate
        if (!isLoading) {
            if (!jJobNumber.getText().trim().equals(labelPrintFrame.getEnergyLabel().getJobNumber().trim())) {
                labelPrintFrame.getEnergyLabel().setJobNumber(jJobNumber.getText().trim());
                labelPrintFrame.setDirty(true);
            }
        }
    }//GEN-LAST:event_jJobNumberCaretUpdate

    private void jProductTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductTypeActionPerformed
        labelPrintFrame.getEnergyLabel().setType((String) jProductType.getSelectedItem());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jProductTypeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAnnualConsumption;
    private javax.swing.JTextField jBrand;
    private javax.swing.JTextField jCapacity;
    private javax.swing.JTextField jCountryOfOrigin;
    private javax.swing.JTextField jDefrost;
    private javax.swing.JTextField jDistributor;
    private javax.swing.JTextField jElectricityRate;
    private javax.swing.JTextField jJobNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLabelName;
    private javax.swing.JTextField jManufacturer;
    private javax.swing.JTextField jModelNo;
    private javax.swing.JTextField jOperatingCost;
    private javax.swing.JComboBox jProductType;
    private javax.swing.JButton jSaveLabel;
    private javax.swing.JTextField jStandardNo;
    private javax.swing.JTextField jValidity;
    private javax.swing.JButton jViewLabel;
    // End of variables declaration//GEN-END:variables
}
