/*
LabelPrint - A general purpose energy label printing application 
Copyright (C) 2018  D P Bennett & Associates Limited

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

Email: info@dpbennett.com.jm
 */
package jm.com.dpbennett.labelprint.ui;

import jm.com.dpbennett.business.entity.EnergyLabel;

public class LabelDataPanel extends javax.swing.JPanel {
    
    private LabelPrintFrame labelPrintFrame;
    private EnergyLabel energyLabel;

    /**
     * Creates new form LabelDataDialog
     */
    public LabelDataPanel() {
        initComponents();
        energyLabel = new EnergyLabel();
    }

    /**
     * Creates new form LabelDataDialog
     *
     * @param labelPrintFrame
     */
    public LabelDataPanel(LabelPrintFrame labelPrintFrame) {
        this.labelPrintFrame = labelPrintFrame;
        initComponents();
        energyLabel = new EnergyLabel();
    }
    
    public EnergyLabel getEnergyLabel() {
        return energyLabel;
    }
    
    public void setEnergyLabel(EnergyLabel energyLabel) {
        this.energyLabel = energyLabel;
    }

    /**
     * Get label data from dialog
     */
    public void getLabelData() {
        
        getEnergyLabel().setDistributor(jDistributor.getText());
        getEnergyLabel().setDefrost(jDefrost.getText());
        getEnergyLabel().setCostPerKwh(jElectricityRate.getText());
        getEnergyLabel().setBrand(jBrand.getText());
        getEnergyLabel().setModel(jModelNo.getText());
        getEnergyLabel().setValidity(jValidity.getText());
        getEnergyLabel().setCapacity(jCapacity.getText());
        getEnergyLabel().setStandard(jStandardNo.getText());
        getEnergyLabel().setOperatingCost(jOperatingCost.getText());
        getEnergyLabel().setManufacturer(jManufacturer.getText());
        getEnergyLabel().setCountry(jCountryOfOrigin.getText());
        getEnergyLabel().setAnnualConsumption(jAnnualConsumption.getText());
        getEnergyLabel().setType(jProductType.getSelectedItem().toString());
        getEnergyLabel().setJobNumber(jJobNumber.getText());
        getEnergyLabel().setLabelName(jLabelName.getText());
        
    }
    
    private void loadLabelData() {
        jDistributor.setText(getEnergyLabel().getDistributor());
        jDefrost.setText(getEnergyLabel().getDefrost());
        jElectricityRate.setText(getEnergyLabel().getCostPerKwh());
        jBrand.setText(getEnergyLabel().getBrand());
        jModelNo.setText(getEnergyLabel().getModel());
        jValidity.setText(getEnergyLabel().getValidity());
        jCapacity.setText(getEnergyLabel().getCapacity());
        jStandardNo.setText(getEnergyLabel().getStandard());
        jOperatingCost.setText(getEnergyLabel().getOperatingCost());
        jManufacturer.setText(getEnergyLabel().getManufacturer());
        jCountryOfOrigin.setText(getEnergyLabel().getCountry());
        jAnnualConsumption.setText(getEnergyLabel().getAnnualConsumption());
        jProductType.setSelectedItem(getEnergyLabel().getType());
        jJobNumber.setText(getEnergyLabel().getJobNumber());
        jLabelName.setText(getEnergyLabel().getLabelName());
        
    }
    
    public void updateLabelData() {
        loadLabelData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jJobNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jProductType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jCapacity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDefrost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDistributor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jManufacturer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBrand = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jModelNo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCountryOfOrigin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jOperatingCost = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jAnnualConsumption = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jElectricityRate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jValidity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jStandardNo = new javax.swing.JTextField();
        jViewLabel = new javax.swing.JButton();
        jSaveLabel = new javax.swing.JButton();

        setName(""); // NOI18N
        setLayout(new java.awt.GridLayout(16, 2, 2, 5));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setLabelFor(jProductType);
        jLabel14.setText("Label Name:");
        add(jLabel14);

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabelNameKeyReleased(evt);
            }
        });
        add(jLabelName);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setLabelFor(jJobNumber);
        jLabel15.setText("Job Number:");
        add(jLabel15);

        jJobNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jJobNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jJobNumberKeyTyped(evt);
            }
        });
        add(jJobNumber);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setLabelFor(jProductType);
        jLabel1.setText("Product Type:");
        add(jLabel1);

        jProductType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic Refrigerator", "Freezer", "Refrigerator", "Room Air-conditioner", " " }));
        jProductType.setSelectedIndex(2);
        jProductType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductTypeActionPerformed(evt);
            }
        });
        add(jProductType);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Capacity (cu. m):");
        add(jLabel2);

        jCapacity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCapacity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCapacityKeyTyped(evt);
            }
        });
        add(jCapacity);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Defrost (Manual/Automatic):");
        add(jLabel3);

        jDefrost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jDefrost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDefrostKeyTyped(evt);
            }
        });
        add(jDefrost);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Distributor:");
        add(jLabel4);

        jDistributor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jDistributor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDistributorKeyTyped(evt);
            }
        });
        add(jDistributor);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Manufacturer:");
        add(jLabel5);

        jManufacturer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jManufacturer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jManufacturerKeyTyped(evt);
            }
        });
        add(jManufacturer);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Brand:");
        add(jLabel6);

        jBrand.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jBrandKeyTyped(evt);
            }
        });
        add(jBrand);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Model No.:");
        add(jLabel7);

        jModelNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jModelNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jModelNoKeyTyped(evt);
            }
        });
        add(jModelNo);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Country of Origin:");
        add(jLabel8);

        jCountryOfOrigin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCountryOfOrigin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCountryOfOriginKeyTyped(evt);
            }
        });
        add(jCountryOfOrigin);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Operating Cost ($/yr):");
        add(jLabel9);

        jOperatingCost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jOperatingCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jOperatingCostKeyTyped(evt);
            }
        });
        add(jOperatingCost);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Anual Consumption (kwh/yr):");
        add(jLabel10);

        jAnnualConsumption.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jAnnualConsumption.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jAnnualConsumptionKeyTyped(evt);
            }
        });
        add(jAnnualConsumption);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Electricity Rate ($/kwh):");
        add(jLabel11);

        jElectricityRate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jElectricityRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jElectricityRateKeyTyped(evt);
            }
        });
        add(jElectricityRate);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Validity (year):");
        add(jLabel12);

        jValidity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jValidity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jValidityKeyTyped(evt);
            }
        });
        add(jValidity);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Standard No.:");
        add(jLabel13);

        jStandardNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jStandardNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jStandardNoKeyTyped(evt);
            }
        });
        add(jStandardNo);

        jViewLabel.setText("View");
        jViewLabel.setToolTipText("View label with current data");
        jViewLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewLabelActionPerformed(evt);
            }
        });
        add(jViewLabel);

        jSaveLabel.setText("Save");
        jSaveLabel.setToolTipText("Save the label data");
        jSaveLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveLabelActionPerformed(evt);
            }
        });
        add(jSaveLabel);
    }// </editor-fold>//GEN-END:initComponents


    private void jSaveLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveLabelActionPerformed
        labelPrintFrame.saveLabel();
    }//GEN-LAST:event_jSaveLabelActionPerformed

    private void jViewLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewLabelActionPerformed
        // Update label and set label view panel     
        labelPrintFrame.getLabelPanel().updateLabel();
        labelPrintFrame.getTabbedPane().setSelectedIndex(1);
    }//GEN-LAST:event_jViewLabelActionPerformed

    private void jProductTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductTypeActionPerformed
        getEnergyLabel().setType((String) jProductType.getSelectedItem());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jProductTypeActionPerformed

    private void jJobNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jJobNumberKeyTyped
        getEnergyLabel().setJobNumber(jJobNumber.getText());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jJobNumberKeyTyped

    private void jLabelNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelNameKeyReleased
        getEnergyLabel().setLabelName(jLabelName.getText());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jLabelNameKeyReleased

    private void jCapacityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCapacityKeyTyped
        getEnergyLabel().setCapacity(jCapacity.getText());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jCapacityKeyTyped

    private void jDefrostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDefrostKeyTyped
        getEnergyLabel().setDefrost(jDefrost.getText());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jDefrostKeyTyped

    private void jDistributorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDistributorKeyTyped
        getEnergyLabel().setDistributor(jDistributor.getText());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jDistributorKeyTyped

    private void jManufacturerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jManufacturerKeyTyped
        getEnergyLabel().setManufacturer(jManufacturer.getText());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jManufacturerKeyTyped

    private void jBrandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBrandKeyTyped
        getEnergyLabel().setBrand(jBrand.getText());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jBrandKeyTyped

    private void jModelNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jModelNoKeyTyped
        getEnergyLabel().setModel(jModelNo.getText());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jModelNoKeyTyped

    private void jCountryOfOriginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCountryOfOriginKeyTyped
        getEnergyLabel().setCountry(jCountryOfOrigin.getText());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jCountryOfOriginKeyTyped

    private void jOperatingCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jOperatingCostKeyTyped
        getEnergyLabel().setOperatingCost(jOperatingCost.getText());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jOperatingCostKeyTyped

    private void jAnnualConsumptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAnnualConsumptionKeyTyped
        getEnergyLabel().setAnnualConsumption(jAnnualConsumption.getText());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jAnnualConsumptionKeyTyped

    private void jElectricityRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jElectricityRateKeyTyped
        getEnergyLabel().setCostPerKwh(jElectricityRate.getText());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jElectricityRateKeyTyped

    private void jValidityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jValidityKeyTyped
        getEnergyLabel().setValidity(jValidity.getText());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jValidityKeyTyped

    private void jStandardNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jStandardNoKeyTyped
        getEnergyLabel().setStandard(jStandardNo.getText());
        labelPrintFrame.setDirty(true);
    }//GEN-LAST:event_jStandardNoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAnnualConsumption;
    private javax.swing.JTextField jBrand;
    private javax.swing.JTextField jCapacity;
    private javax.swing.JTextField jCountryOfOrigin;
    private javax.swing.JTextField jDefrost;
    private javax.swing.JTextField jDistributor;
    private javax.swing.JTextField jElectricityRate;
    private javax.swing.JTextField jJobNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLabelName;
    private javax.swing.JTextField jManufacturer;
    private javax.swing.JTextField jModelNo;
    private javax.swing.JTextField jOperatingCost;
    private javax.swing.JComboBox jProductType;
    private javax.swing.JButton jSaveLabel;
    private javax.swing.JTextField jStandardNo;
    private javax.swing.JTextField jValidity;
    private javax.swing.JButton jViewLabel;
    // End of variables declaration//GEN-END:variables
}
