/*
LabelPrint - A general purpose energy label printing application 
Copyright (C) 2018  D P Bennett & Associates Limited

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

Email: info@dpbennett.com.jm
 */
package jm.com.dpbennett.labelprint.ui;

import javax.swing.JOptionPane;
import jm.com.dpbennett.labelprint.Options;

/**
 * Uses the system properties file to edit system properties.
 *
 * @author Desmond Bennett
 */
public class OptionsJDialog extends javax.swing.JDialog {

    private boolean isDirty;
    private LabelPrintFrame labelPrintFrame;

    public OptionsJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();

        init(parent);

    }

    private void init(java.awt.Frame parent) {
        String[][] fieldsToSearch;
        labelPrintFrame = (LabelPrintFrame) parent;
        setLocationRelativeTo(null);

        // Load existing options
        Options sysOptions = labelPrintFrame.getSystemOptions();
        // Notes tab
        jNote1_1_TextArea.setText(sysOptions.getProperty("Note1_1"));
        jNote1_2_TextArea.setText(sysOptions.getProperty("Note1_2"));
        jNote2_1_TextArea.setText(sysOptions.getProperty("Note2_1"));
        jNote2_2_TextArea.setText(sysOptions.getProperty("Note2_2"));
        jNote3_1_TextArea.setText(sysOptions.getProperty("Note3_1"));
        jNote3_2_TextArea.setText(sysOptions.getProperty("Note3_2"));
        jNote3_3_TextArea.setText(sysOptions.getProperty("Note3_3"));
        // Database tab
        jDatabaseURLTextField.setText(sysOptions.getProperty("ConnectionURL"));
        jUsernameTextField.setText(sysOptions.getProperty("ConnectionUserName"));
        jPasswordField.setText(sysOptions.getConnectionPassword());
        fieldsToSearch = sysOptions.getFieldsToSearch();
        for (int i = 0; i < fieldsToSearch.length; ++i) {
            jDefaultSearchFieldComboBox.addItem(fieldsToSearch[i][0]);
        }
        jDefaultSearchFieldComboBox.setSelectedItem(sysOptions.getProperty("DefaultFieldToSearch"));
        jConnectToDatabaseCheckBox.setSelected(sysOptions.isConnectToDatabase());
        // Label Content tab  
        // Image Export Formats
        jJPEG.setSelected(sysOptions.isExportJPEG());
        jGIF.setSelected(sysOptions.isExportGIF());
        jPNG.setSelected(sysOptions.isExportPNG());
        jPDF.setSelected(sysOptions.isExportPDF());
        // Label defaults
        jRatedVoltage.setSelectedItem(sysOptions.getProperty("DefaultRatedVoltage"));
        jRatedFrequency.setSelectedItem(sysOptions.getProperty("DefaultRatedFrequency"));
        jStandardNo.setSelectedItem(sysOptions.getProperty("Standard"));
        jProductType.setSelectedItem(sysOptions.getProperty("DefaultProductType"));

        isDirty = false;
    }

    public boolean hasDatabaseConnectionOptionsChanged() {
        return isDirty;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionsTabbedPane = new javax.swing.JTabbedPane();
        jLabelContentPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jNote1_1_TextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jNote1_2_TextArea = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jNote2_1_TextArea = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jNote3_1_TextArea = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jNote2_2_TextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jNote3_2_TextArea = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jNote3_3_TextArea = new javax.swing.JTextArea();
        jDatabasePanel = new javax.swing.JPanel();
        jDatabaseOptionsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDatabaseURLTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jUsernameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jDefaultSearchFieldComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jConnectToDatabaseCheckBox = new javax.swing.JCheckBox();
        jMiscellaneousPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jJPEG = new javax.swing.JCheckBox();
        jPNG = new javax.swing.JCheckBox();
        jGIF = new javax.swing.JCheckBox();
        jPDF = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRatedVoltage = new javax.swing.JComboBox<>();
        jRatedFrequency = new javax.swing.JComboBox<>();
        jProductType = new javax.swing.JComboBox<>();
        jProductTypeDetail = new javax.swing.JComboBox<>();
        jProductClass = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jStandardNo = new javax.swing.JComboBox<>();
        jOk = new javax.swing.JButton();
        jCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");
        setResizable(false);

        jNote1_1_TextArea.setColumns(20);
        jNote1_1_TextArea.setLineWrap(true);
        jNote1_1_TextArea.setRows(2);
        jNote1_1_TextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNote1_1_TextAreaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jNote1_1_TextArea);

        jNote1_2_TextArea.setColumns(20);
        jNote1_2_TextArea.setLineWrap(true);
        jNote1_2_TextArea.setRows(2);
        jNote1_2_TextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNote1_2_TextAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jNote1_2_TextArea);

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel12.setText("Test standard note:");

        jNote2_1_TextArea.setColumns(20);
        jNote2_1_TextArea.setLineWrap(true);
        jNote2_1_TextArea.setRows(1);
        jNote2_1_TextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNote2_1_TextAreaKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jNote2_1_TextArea);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel13.setText("Violation note:");

        jNote3_1_TextArea.setColumns(20);
        jNote3_1_TextArea.setLineWrap(true);
        jNote3_1_TextArea.setRows(1);
        jNote3_1_TextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNote3_1_TextAreaKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jNote3_1_TextArea);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setText("Energy consumption note:");

        jNote2_2_TextArea.setColumns(20);
        jNote2_2_TextArea.setLineWrap(true);
        jNote2_2_TextArea.setRows(1);
        jNote2_2_TextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNote2_2_TextAreaKeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(jNote2_2_TextArea);

        jNote3_2_TextArea.setColumns(20);
        jNote3_2_TextArea.setLineWrap(true);
        jNote3_2_TextArea.setRows(1);
        jNote3_2_TextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNote3_2_TextAreaKeyReleased(evt);
            }
        });
        jScrollPane6.setViewportView(jNote3_2_TextArea);

        jNote3_3_TextArea.setColumns(20);
        jNote3_3_TextArea.setLineWrap(true);
        jNote3_3_TextArea.setRows(1);
        jNote3_3_TextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNote3_3_TextAreaKeyReleased(evt);
            }
        });
        jScrollPane7.setViewportView(jNote3_3_TextArea);

        javax.swing.GroupLayout jLabelContentPanelLayout = new javax.swing.GroupLayout(jLabelContentPanel);
        jLabelContentPanel.setLayout(jLabelContentPanelLayout);
        jLabelContentPanelLayout.setHorizontalGroup(
            jLabelContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLabelContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLabelContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        jLabelContentPanelLayout.setVerticalGroup(
            jLabelContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLabelContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jLabelContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLabelContentPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jLabelContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jLabelContentPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jOptionsTabbedPane.addTab("Label Notes", jLabelContentPanel);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Database URL:");

        jDatabaseURLTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jDatabaseURLTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDatabaseURLTextFieldKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Username:");

        jUsernameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jUsernameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jUsernameTextFieldKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Password:");

        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Default search field:");

        jDefaultSearchFieldComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jDefaultSearchFieldComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDefaultSearchFieldComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Connect to database:");

        jConnectToDatabaseCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jConnectToDatabaseCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConnectToDatabaseCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDatabaseOptionsPanelLayout = new javax.swing.GroupLayout(jDatabaseOptionsPanel);
        jDatabaseOptionsPanel.setLayout(jDatabaseOptionsPanelLayout);
        jDatabaseOptionsPanelLayout.setHorizontalGroup(
            jDatabaseOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDatabaseOptionsPanelLayout.createSequentialGroup()
                .addGroup(jDatabaseOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDatabaseOptionsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jDatabaseURLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDatabaseOptionsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jUsernameTextField))
                    .addGroup(jDatabaseOptionsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jPasswordField))
                    .addGroup(jDatabaseOptionsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jDefaultSearchFieldComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDatabaseOptionsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jConnectToDatabaseCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jDatabaseOptionsPanelLayout.setVerticalGroup(
            jDatabaseOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDatabaseOptionsPanelLayout.createSequentialGroup()
                .addGroup(jDatabaseOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDatabaseURLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jDatabaseOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jDatabaseOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jDatabaseOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDefaultSearchFieldComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jDatabaseOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConnectToDatabaseCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jDatabasePanelLayout = new javax.swing.GroupLayout(jDatabasePanel);
        jDatabasePanel.setLayout(jDatabasePanelLayout);
        jDatabasePanelLayout.setHorizontalGroup(
            jDatabasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDatabasePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jDatabaseOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDatabasePanelLayout.setVerticalGroup(
            jDatabasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDatabasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDatabaseOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jOptionsTabbedPane.addTab("Database", jDatabasePanel);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Image export formats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 153))); // NOI18N

        jJPEG.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jJPEG.setText("JPEG");
        jJPEG.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jJPEG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJPEGActionPerformed(evt);
            }
        });

        jPNG.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jPNG.setText("PNG");
        jPNG.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPNGActionPerformed(evt);
            }
        });

        jGIF.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jGIF.setText("GIF");
        jGIF.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jGIF.setEnabled(false);
        jGIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGIFActionPerformed(evt);
            }
        });

        jPDF.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jPDF.setText("PDF");
        jPDF.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPDF.setEnabled(false);
        jPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPDF)
                    .addComponent(jPNG)
                    .addComponent(jGIF)
                    .addComponent(jJPEG))
                .addGap(0, 125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jJPEG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPNG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jGIF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPDF)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Label Defaults", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 153))); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Standard No.:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Product Type:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Rated Voltage:");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Rated Frequency:");

        jRatedVoltage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "110", "115", "120", "125", "220", "230", "240", "110/220", "115/230", "120/240" }));
        jRatedVoltage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRatedVoltageActionPerformed(evt);
            }
        });

        jRatedFrequency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50", "60", "50/60" }));
        jRatedFrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRatedFrequencyActionPerformed(evt);
            }
        });

        jProductType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basic Refrigerator", "Freezer", "Refrigerator", "Room Air-conditioner" }));
        jProductType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductTypeActionPerformed(evt);
            }
        });

        jProductTypeDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductTypeDetailActionPerformed(evt);
            }
        });

        jProductClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductClassActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Product Type Detail:");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Product Class:");

        jStandardNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JS 178", "JS 179" }));
        jStandardNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStandardNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel6)
                                .addComponent(jLabel11)))
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRatedFrequency, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRatedVoltage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProductType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProductTypeDetail, 0, 409, Short.MAX_VALUE)
                    .addComponent(jProductClass, 0, 409, Short.MAX_VALUE)
                    .addComponent(jStandardNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRatedVoltage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jRatedFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jStandardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jProductType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProductTypeDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProductClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jMiscellaneousPanelLayout = new javax.swing.GroupLayout(jMiscellaneousPanel);
        jMiscellaneousPanel.setLayout(jMiscellaneousPanelLayout);
        jMiscellaneousPanelLayout.setHorizontalGroup(
            jMiscellaneousPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMiscellaneousPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMiscellaneousPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jMiscellaneousPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 418, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jMiscellaneousPanelLayout.setVerticalGroup(
            jMiscellaneousPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMiscellaneousPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jOptionsTabbedPane.addTab("Label Content", jMiscellaneousPanel);

        jOk.setText("Ok");
        jOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkActionPerformed(evt);
            }
        });

        jCancel.setText("Cancel");
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jOptionsTabbedPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jOk)
                .addGap(18, 18, 18)
                .addComponent(jCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCancel, jOk});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jOptionsTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancel)
                    .addComponent(jOk))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jConnectToDatabaseCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConnectToDatabaseCheckBoxActionPerformed

        isDirty = true;
    }//GEN-LAST:event_jConnectToDatabaseCheckBoxActionPerformed

    private void jOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkActionPerformed
        Options sysOptions = labelPrintFrame.getSystemOptions();

        // Label Notes
        sysOptions.setProperty("Note1_1", jNote1_1_TextArea.getText());
        sysOptions.setProperty("Note1_2", jNote1_2_TextArea.getText());
        sysOptions.setProperty("Note2_1", jNote2_1_TextArea.getText());
        sysOptions.setProperty("Note2_2", jNote2_2_TextArea.getText());
        sysOptions.setProperty("Note3_1", jNote3_1_TextArea.getText());
        sysOptions.setProperty("Note3_2", jNote3_2_TextArea.getText());
        sysOptions.setProperty("Note3_3", jNote3_3_TextArea.getText());
        // Database
        sysOptions.setProperty("DefaultFieldToSearch", 
                jDefaultSearchFieldComboBox.getSelectedItem().toString());
        char[] password = jPasswordField.getPassword();
        String passwordString = new String(password).trim();
        sysOptions.setConnectionPassword(passwordString);
        sysOptions.setProperty("ConnectionUserName", jUsernameTextField.getText().trim());
        sysOptions.setProperty("ConnectionURL", jDatabaseURLTextField.getText().trim());
        sysOptions.setConnectToDatabase(jConnectToDatabaseCheckBox.isSelected());
        // Label Content
        // Image export formats
        sysOptions.setExportPDF(jPDF.isSelected());
        sysOptions.setExportPNG(jPNG.isSelected());
        sysOptions.setExportGIF(jGIF.isSelected());
        sysOptions.setExportJPEG(jJPEG.isSelected());
        // Label defaults
        sysOptions.setProperty("DefaultRatedVoltage", 
                jRatedVoltage.getSelectedItem().toString());
        sysOptions.setProperty("DefaultRatedFrequency", 
                jRatedFrequency.getSelectedItem().toString());
        //sysOptions.setProperty("DefaultProductTypeDetail", jProductType.getText());    
        sysOptions.setProperty("Standard", jStandardNo.getSelectedItem().toString());
        sysOptions.setProperty("DefaultProductType", 
                jProductType.getSelectedItem().toString());        

        sysOptions.write();

        // Update relevant views that are dependent on system options
        java.awt.EventQueue.invokeLater(() -> {
            if (labelPrintFrame.getLabelPanel() != null) {
                labelPrintFrame.getLabelPanel().updateLabel();
            }
        });

        // Test the database connection
        if (sysOptions.isConnectToDatabase()) {
            System.out.println("will try to setup db with user:"
                    + sysOptions.getProperty("ConnectionUserName"));
            if (labelPrintFrame.setupDatabaseConnection()) {

                labelPrintFrame.setStatus("Ready...");
                dispose();
            } else {
                labelPrintFrame.setStatus("A database connection error occurred!");
                JOptionPane.showMessageDialog(this,
                        "A database connection error occurred.\n"
                        + "Check that the database options are valid",
                        "Database Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            dispose();
        }

    }//GEN-LAST:event_jOkActionPerformed

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        isDirty = false;
        dispose();
    }//GEN-LAST:event_jCancelActionPerformed

    private void jDefaultSearchFieldComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDefaultSearchFieldComboBoxActionPerformed
        isDirty = true;
    }//GEN-LAST:event_jDefaultSearchFieldComboBoxActionPerformed

    private void jRatedVoltageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRatedVoltageActionPerformed
        isDirty = true;
    }//GEN-LAST:event_jRatedVoltageActionPerformed

    private void jRatedFrequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRatedFrequencyActionPerformed
        isDirty = true;
    }//GEN-LAST:event_jRatedFrequencyActionPerformed

    private void jNote1_1_TextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNote1_1_TextAreaKeyReleased
        isDirty = true;
    }//GEN-LAST:event_jNote1_1_TextAreaKeyReleased

    private void jNote1_2_TextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNote1_2_TextAreaKeyReleased
        isDirty = true;
    }//GEN-LAST:event_jNote1_2_TextAreaKeyReleased

    private void jNote2_1_TextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNote2_1_TextAreaKeyReleased
        isDirty = true;
    }//GEN-LAST:event_jNote2_1_TextAreaKeyReleased

    private void jNote2_2_TextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNote2_2_TextAreaKeyReleased
        isDirty = true;
    }//GEN-LAST:event_jNote2_2_TextAreaKeyReleased

    private void jNote3_1_TextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNote3_1_TextAreaKeyReleased
        isDirty = true;
    }//GEN-LAST:event_jNote3_1_TextAreaKeyReleased

    private void jNote3_2_TextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNote3_2_TextAreaKeyReleased
        isDirty = true;
    }//GEN-LAST:event_jNote3_2_TextAreaKeyReleased

    private void jNote3_3_TextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNote3_3_TextAreaKeyReleased
        isDirty = true;
    }//GEN-LAST:event_jNote3_3_TextAreaKeyReleased

    private void jDatabaseURLTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDatabaseURLTextFieldKeyReleased
        isDirty = true;
    }//GEN-LAST:event_jDatabaseURLTextFieldKeyReleased

    private void jUsernameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameTextFieldKeyReleased
        isDirty = true;
    }//GEN-LAST:event_jUsernameTextFieldKeyReleased

    private void jPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyReleased
        isDirty = true;
    }//GEN-LAST:event_jPasswordFieldKeyReleased

    private void jJPEGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJPEGActionPerformed
        isDirty = true;
    }//GEN-LAST:event_jJPEGActionPerformed

    private void jPNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPNGActionPerformed
        isDirty = true;
    }//GEN-LAST:event_jPNGActionPerformed

    private void jGIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGIFActionPerformed
        isDirty = true;
    }//GEN-LAST:event_jGIFActionPerformed

    private void jPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPDFActionPerformed
        isDirty = true;
    }//GEN-LAST:event_jPDFActionPerformed

    private void jProductTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductTypeActionPerformed
        isDirty = true;
    }//GEN-LAST:event_jProductTypeActionPerformed

    private void jProductTypeDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductTypeDetailActionPerformed
        isDirty = true;
    }//GEN-LAST:event_jProductTypeDetailActionPerformed

    private void jProductClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductClassActionPerformed
        isDirty = true;
    }//GEN-LAST:event_jProductClassActionPerformed

    private void jStandardNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStandardNoActionPerformed
        isDirty = true;
    }//GEN-LAST:event_jStandardNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new OptionsJDialog(new javax.swing.JFrame(), true).setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancel;
    private javax.swing.JCheckBox jConnectToDatabaseCheckBox;
    private javax.swing.JPanel jDatabaseOptionsPanel;
    private javax.swing.JPanel jDatabasePanel;
    private javax.swing.JTextField jDatabaseURLTextField;
    private javax.swing.JComboBox jDefaultSearchFieldComboBox;
    private javax.swing.JCheckBox jGIF;
    private javax.swing.JCheckBox jJPEG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jLabelContentPanel;
    private javax.swing.JPanel jMiscellaneousPanel;
    private javax.swing.JTextArea jNote1_1_TextArea;
    private javax.swing.JTextArea jNote1_2_TextArea;
    private javax.swing.JTextArea jNote2_1_TextArea;
    private javax.swing.JTextArea jNote2_2_TextArea;
    private javax.swing.JTextArea jNote3_1_TextArea;
    private javax.swing.JTextArea jNote3_2_TextArea;
    private javax.swing.JTextArea jNote3_3_TextArea;
    private javax.swing.JButton jOk;
    private javax.swing.JTabbedPane jOptionsTabbedPane;
    private javax.swing.JCheckBox jPDF;
    private javax.swing.JCheckBox jPNG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JComboBox<String> jProductClass;
    private javax.swing.JComboBox<String> jProductType;
    private javax.swing.JComboBox<String> jProductTypeDetail;
    private javax.swing.JComboBox<String> jRatedFrequency;
    private javax.swing.JComboBox<String> jRatedVoltage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JComboBox<String> jStandardNo;
    private javax.swing.JTextField jUsernameTextField;
    // End of variables declaration//GEN-END:variables
}
