/*
LabelPrint - A general purpose energy label printing application 
Copyright (C) 2018  D P Bennett & Associates Limited

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

Email: info@dpbennett.com.jm
 */
package jm.com.dpbennett.labelprint.ui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import jm.com.dpbennett.labelprint.LabelPrintFileFilter;
import jm.com.dpbennett.labelprint.SystemOptions;

/**
 *
 * @author  Desmond Bennett
 */
public class OptionsJDialog extends javax.swing.JDialog {

    private boolean databaseConnectionOptionsChanged;
    private LabelPrintFrame labelPrintFrame;
    private boolean bLoadingComboBox;

    /** Creates new form OptionsJDialog */
    public OptionsJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        String[][] fieldsToSearch;

        initComponents();
        labelPrintFrame = (LabelPrintFrame) parent;
        setLocationRelativeTo(null);

        // Load existing options
        SystemOptions sysOptions = labelPrintFrame.getSystemOptions();
        fieldsToSearch = sysOptions.getFieldsToSearch();
        // Init General Options tab
        // Export formats
        jJPEGCheckBox.setSelected(sysOptions.isExportJPEG());
        jGIFCheckBox.setSelected(sysOptions.isExportGIF());
        jPNGCheckBox.setSelected(sysOptions.isExportPNG());
        jPDFCheckBox.setSelected(sysOptions.isExportPDF());        
        // Init Database Options tab
        jDatabaseURLTextField.setText(sysOptions.getConnectionURL());
        jUsernameTextField.setText(sysOptions.getConnectionUserName());
        jPasswordField.setText(sysOptions.getConnectionPassword());
        // Init field to search combobox
        bLoadingComboBox = true;
        for (int i = 0; i < fieldsToSearch.length; ++i) {
            jDefaultSearchFieldComboBox.addItem(fieldsToSearch[i][0]);
        }
        jDefaultSearchFieldComboBox.setSelectedItem(sysOptions.getDefaultFieldToSearch());
        // Store in database
        jConnectToDatabaseCheckBox.setSelected(sysOptions.isConnectToDatabase());
        bLoadingComboBox = false;
        
        // Label Content tab
        jNote1_1_TextArea.setText(sysOptions.getNote1_1());
        jNote1_2_TextArea.setText(sysOptions.getNote2());
        jNote2_1_TextArea.setText(sysOptions.getNote3());
        jNote3_1_TextArea.setText(sysOptions.getNote4());

        databaseConnectionOptionsChanged = false;

    }

    public boolean hasDatabaseConnectionOptionsChanged() {
        return databaseConnectionOptionsChanged;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabelContentPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jNote1_1_TextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jNote1_2_TextArea = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jNote2_1_TextArea = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jNote3_1_TextArea = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jNote2_2_TextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jNote3_2_TextArea = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jNote3_3_TextArea = new javax.swing.JTextArea();
        jDatabasePanel = new javax.swing.JPanel();
        jDatabaseOptionsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDatabaseURLTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jUsernameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jDefaultSearchFieldComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jConnectToDatabaseCheckBox = new javax.swing.JCheckBox();
        jExportPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jJPEGCheckBox = new javax.swing.JCheckBox();
        jPNGCheckBox = new javax.swing.JCheckBox();
        jGIFCheckBox = new javax.swing.JCheckBox();
        jPDFCheckBox = new javax.swing.JCheckBox();
        jOkButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");
        setResizable(false);

        jNote1_1_TextArea.setColumns(20);
        jNote1_1_TextArea.setLineWrap(true);
        jNote1_1_TextArea.setRows(2);
        jNote1_1_TextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jNote1_1_TextAreaCaretUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(jNote1_1_TextArea);

        jNote1_2_TextArea.setColumns(20);
        jNote1_2_TextArea.setLineWrap(true);
        jNote1_2_TextArea.setRows(2);
        jNote1_2_TextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jNote1_2_TextAreaCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(jNote1_2_TextArea);

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel12.setText("Test standard note:");

        jNote2_1_TextArea.setColumns(20);
        jNote2_1_TextArea.setLineWrap(true);
        jNote2_1_TextArea.setRows(1);
        jNote2_1_TextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jNote2_1_TextAreaCaretUpdate(evt);
            }
        });
        jScrollPane3.setViewportView(jNote2_1_TextArea);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel13.setText("Violation note:");

        jNote3_1_TextArea.setColumns(20);
        jNote3_1_TextArea.setLineWrap(true);
        jNote3_1_TextArea.setRows(1);
        jNote3_1_TextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jNote3_1_TextAreaCaretUpdate(evt);
            }
        });
        jScrollPane4.setViewportView(jNote3_1_TextArea);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setText("Energy consumption note:");

        jNote2_2_TextArea.setColumns(20);
        jNote2_2_TextArea.setLineWrap(true);
        jNote2_2_TextArea.setRows(1);
        jNote2_2_TextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jNote2_2_TextAreaCaretUpdate(evt);
            }
        });
        jScrollPane5.setViewportView(jNote2_2_TextArea);

        jNote3_2_TextArea.setColumns(20);
        jNote3_2_TextArea.setLineWrap(true);
        jNote3_2_TextArea.setRows(1);
        jNote3_2_TextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jNote3_2_TextAreaCaretUpdate(evt);
            }
        });
        jScrollPane6.setViewportView(jNote3_2_TextArea);

        jNote3_3_TextArea.setColumns(20);
        jNote3_3_TextArea.setLineWrap(true);
        jNote3_3_TextArea.setRows(1);
        jNote3_3_TextArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jNote3_3_TextAreaCaretUpdate(evt);
            }
        });
        jScrollPane7.setViewportView(jNote3_3_TextArea);

        javax.swing.GroupLayout jLabelContentPanelLayout = new javax.swing.GroupLayout(jLabelContentPanel);
        jLabelContentPanel.setLayout(jLabelContentPanelLayout);
        jLabelContentPanelLayout.setHorizontalGroup(
            jLabelContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLabelContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLabelContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        jLabelContentPanelLayout.setVerticalGroup(
            jLabelContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLabelContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jLabelContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLabelContentPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jLabelContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jLabelContentPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Label Content", jLabelContentPanel);

        jDatabaseOptionsPanel.setLayout(new java.awt.GridLayout(5, 2, 2, 25));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Database URL:");
        jDatabaseOptionsPanel.add(jLabel1);

        jDatabaseURLTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jDatabaseURLTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jDatabaseURLTextFieldCaretUpdate(evt);
            }
        });
        jDatabaseOptionsPanel.add(jDatabaseURLTextField);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Username:");
        jDatabaseOptionsPanel.add(jLabel2);

        jUsernameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jUsernameTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jUsernameTextFieldCaretUpdate(evt);
            }
        });
        jDatabaseOptionsPanel.add(jUsernameTextField);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Password:");
        jDatabaseOptionsPanel.add(jLabel5);

        jPasswordField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jPasswordFieldCaretUpdate(evt);
            }
        });
        jDatabaseOptionsPanel.add(jPasswordField);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Default search field:");
        jDatabaseOptionsPanel.add(jLabel3);

        jDefaultSearchFieldComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jDefaultSearchFieldComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDefaultSearchFieldComboBoxActionPerformed(evt);
            }
        });
        jDatabaseOptionsPanel.add(jDefaultSearchFieldComboBox);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Connect to database:");
        jDatabaseOptionsPanel.add(jLabel4);

        jConnectToDatabaseCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jConnectToDatabaseCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConnectToDatabaseCheckBoxActionPerformed(evt);
            }
        });
        jDatabaseOptionsPanel.add(jConnectToDatabaseCheckBox);

        javax.swing.GroupLayout jDatabasePanelLayout = new javax.swing.GroupLayout(jDatabasePanel);
        jDatabasePanel.setLayout(jDatabasePanelLayout);
        jDatabasePanelLayout.setHorizontalGroup(
            jDatabasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDatabasePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jDatabaseOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jDatabasePanelLayout.setVerticalGroup(
            jDatabasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDatabasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDatabaseOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Database", jDatabasePanel);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "File/image export format", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 153))); // NOI18N

        jJPEGCheckBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jJPEGCheckBox.setText("JPEG");
        jJPEGCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        jPNGCheckBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jPNGCheckBox.setText("PNG");
        jPNGCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        jGIFCheckBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jGIFCheckBox.setText("GIF");
        jGIFCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        jPDFCheckBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jPDFCheckBox.setText("PDF");
        jPDFCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jJPEGCheckBox)
                    .addComponent(jPNGCheckBox)
                    .addComponent(jGIFCheckBox)
                    .addComponent(jPDFCheckBox))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jJPEGCheckBox)
                .addGap(14, 14, 14)
                .addComponent(jPNGCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jGIFCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPDFCheckBox)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jExportPanelLayout = new javax.swing.GroupLayout(jExportPanel);
        jExportPanel.setLayout(jExportPanelLayout);
        jExportPanelLayout.setHorizontalGroup(
            jExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jExportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jExportPanelLayout.setVerticalGroup(
            jExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jExportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Export", jExportPanel);

        jOkButton.setText("Ok");
        jOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkButtonActionPerformed(evt);
            }
        });

        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jOkButton)
                .addGap(17, 17, 17)
                .addComponent(jCancelButton)
                .addGap(254, 254, 254))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCancelButton, jOkButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jOkButton)
                    .addComponent(jCancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jPasswordFieldCaretUpdate
        databaseConnectionOptionsChanged = true;
    }//GEN-LAST:event_jPasswordFieldCaretUpdate

    private void jUsernameTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jUsernameTextFieldCaretUpdate
        databaseConnectionOptionsChanged = true;
    }//GEN-LAST:event_jUsernameTextFieldCaretUpdate

    private void jDatabaseURLTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jDatabaseURLTextFieldCaretUpdate
        databaseConnectionOptionsChanged = true;
    }//GEN-LAST:event_jDatabaseURLTextFieldCaretUpdate

    private void jConnectToDatabaseCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConnectToDatabaseCheckBoxActionPerformed

        databaseConnectionOptionsChanged = true;
    }//GEN-LAST:event_jConnectToDatabaseCheckBoxActionPerformed

    private String getImageFileAbsolutePath() {
        JFileChooser chooser = new JFileChooser();
        LabelPrintFileFilter labelPrintFileFilter = new LabelPrintFileFilter();
        labelPrintFileFilter.addExtension("gif");
        labelPrintFileFilter.addExtension("jpg");
        labelPrintFileFilter.setDescription("Gif and JPEG Images");
        chooser.setFileFilter(labelPrintFileFilter);
        chooser.setCurrentDirectory(new File(".\\images"));
        chooser.showDialog(this, "Choose");
        File file = chooser.getSelectedFile();
        if (file != null) {
            return file.getAbsolutePath();
        }

        return null;
    }

    private void setImageFileAbsolutePath(JTextField textField) {
        String fileName = getImageFileAbsolutePath();

        if (fileName != null) {
            textField.setText(fileName);
        }
    }

    private void jOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkButtonActionPerformed
        SystemOptions sysOptions = labelPrintFrame.getSystemOptions();
        
        // Notes
        sysOptions.setNote1(jNote1_1_TextArea.getText());
        sysOptions.setNote2(jNote1_2_TextArea.getText());
        sysOptions.setNote3(jNote2_1_TextArea.getText());
        sysOptions.setNote4(jNote3_1_TextArea.getText());

        // Update export checkboxes
        sysOptions.setExportPDF(jPDFCheckBox.isSelected());
        sysOptions.setExportPNG(jPNGCheckBox.isSelected());
        sysOptions.setExportGIF(jGIFCheckBox.isSelected());
        sysOptions.setExportJPEG(jJPEGCheckBox.isSelected());
        // Store labels
        sysOptions.setConnectToDatabase(jConnectToDatabaseCheckBox.isSelected());

        // Default field to search
        String selectedField = jDefaultSearchFieldComboBox.getSelectedItem().toString().trim();
        sysOptions.setDefaultFieldToSearch(selectedField);

        // Update password
        char[] password = jPasswordField.getPassword();
        String passwordString = new String(password).trim();
        sysOptions.setConnectionPassword(passwordString);

        sysOptions.setConnectionUserName(jUsernameTextField.getText().trim());
        sysOptions.setConnectionURL(jDatabaseURLTextField.getText().trim());
        sysOptions.writeSystemData();
        
        // Update relevant views that are dependent on system options
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                labelPrintFrame.getLabelPanel().updateLabel();
            }
            
        });
        
        // test the database connection
        if (sysOptions.isConnectToDatabase()) {
            System.out.println("will try to setup db with user:" + sysOptions.getConnectionUserName());
            if (labelPrintFrame.setupDatabaseConnection()) {
                System.out.println("db setup!");
                dispose();
            } else {
                //sysOptions.setConnectToDatabase(false);
                JOptionPane.showMessageDialog(this,
                        "A database connection error occurred.\n"
                        + "Check that the database options are valid",
                        "Database Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            dispose();
        }

    }//GEN-LAST:event_jOkButtonActionPerformed

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        databaseConnectionOptionsChanged = false;
        dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jDefaultSearchFieldComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDefaultSearchFieldComboBoxActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jDefaultSearchFieldComboBoxActionPerformed

    private void jNote1_1_TextAreaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jNote1_1_TextAreaCaretUpdate
        databaseConnectionOptionsChanged = true;
    }//GEN-LAST:event_jNote1_1_TextAreaCaretUpdate

    private void jNote1_2_TextAreaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jNote1_2_TextAreaCaretUpdate
        databaseConnectionOptionsChanged = true;
    }//GEN-LAST:event_jNote1_2_TextAreaCaretUpdate

    private void jNote2_1_TextAreaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jNote2_1_TextAreaCaretUpdate
        databaseConnectionOptionsChanged = true;
    }//GEN-LAST:event_jNote2_1_TextAreaCaretUpdate

    private void jNote3_1_TextAreaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jNote3_1_TextAreaCaretUpdate
        databaseConnectionOptionsChanged = true;
    }//GEN-LAST:event_jNote3_1_TextAreaCaretUpdate

    private void jNote2_2_TextAreaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jNote2_2_TextAreaCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jNote2_2_TextAreaCaretUpdate

    private void jNote3_2_TextAreaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jNote3_2_TextAreaCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jNote3_2_TextAreaCaretUpdate

    private void jNote3_3_TextAreaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jNote3_3_TextAreaCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jNote3_3_TextAreaCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new OptionsJDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelButton;
    private javax.swing.JCheckBox jConnectToDatabaseCheckBox;
    private javax.swing.JPanel jDatabaseOptionsPanel;
    private javax.swing.JPanel jDatabasePanel;
    private javax.swing.JTextField jDatabaseURLTextField;
    private javax.swing.JComboBox jDefaultSearchFieldComboBox;
    private javax.swing.JPanel jExportPanel;
    private javax.swing.JCheckBox jGIFCheckBox;
    private javax.swing.JCheckBox jJPEGCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jLabelContentPanel;
    private javax.swing.JTextArea jNote1_1_TextArea;
    private javax.swing.JTextArea jNote1_2_TextArea;
    private javax.swing.JTextArea jNote2_1_TextArea;
    private javax.swing.JTextArea jNote2_2_TextArea;
    private javax.swing.JTextArea jNote3_1_TextArea;
    private javax.swing.JTextArea jNote3_2_TextArea;
    private javax.swing.JTextArea jNote3_3_TextArea;
    private javax.swing.JButton jOkButton;
    private javax.swing.JCheckBox jPDFCheckBox;
    private javax.swing.JCheckBox jPNGCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jUsernameTextField;
    // End of variables declaration//GEN-END:variables
}
