/*
LabelPrint - A general purpose energy label printing application 
Copyright (C) 2018  D P Bennett & Associates Limited

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

Email: info@dpbennett.com.jm
 */
package jm.com.dpbennett.labelprint.ui;

import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.net.URL;
import org.apache.batik.swing.JSVGCanvas;
import org.apache.batik.swing.svg.SVGLoadEventDispatcherAdapter;
import org.apache.batik.swing.svg.SVGLoadEventDispatcherEvent;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

/**
 *
 * @author dbennett
 */
public class SVGLabelPanel extends javax.swing.JPanel implements Printable {

    private boolean chkGreenBackground;
    private boolean chkYellowBackground;
    private boolean chkContents = true;
    private LabelPrintFrame labelPrintFrame;
    private int m_maxNumPage = 1;
    private JSVGCanvas svgCanvas;
    private Document svgDocument;

    /**
     * Creates new form LabelPanel
     */
    public SVGLabelPanel() {
        initComponents();
        initLabel();
    }

    /**
     * Creates new form LabelPanel
     *
     * @param labelPrintFrame
     */
    public SVGLabelPanel(jm.com.dpbennett.labelprint.ui.LabelPrintFrame labelPrintFrame) {
        this.labelPrintFrame = labelPrintFrame;
        initComponents();
        initLabel();

    }

    private void initLabel() {
        svgCanvas = new JSVGCanvas();
        svgCanvas.setDocumentState(JSVGCanvas.ALWAYS_DYNAMIC);
        URL url = getClass().getClassLoader().getResource("images/EnergyLabel.svg");
        svgCanvas.setURI(url.toString());
        svgCanvas.addSVGLoadEventDispatcherListener(new SVGLoadEventDispatcherAdapter() {
            @Override
            public void svgLoadEventDispatchStarted(SVGLoadEventDispatcherEvent e) {
                // At this time the document is available so get it.
                svgDocument = svgCanvas.getSVGDocument();
            }
        });

        add("Center", svgCanvas);
    }

    private void setElementText(String elementId, String content) {
        if (svgDocument != null) {
            Element element = svgDocument.getElementById(elementId);
            element.setTextContent(content);
        }
    }

    public void showGreenBackground(boolean flag) {
        chkGreenBackground = flag;
    }

    public void showYellowBackground(boolean flag) {
        chkYellowBackground = flag;
    }

    public void showContents(boolean flag) {
        chkContents = flag;
    }

    public boolean exportLabelToRasterGraphic(String fileName, String formatName) {

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPanel = new javax.swing.JPanel();
        jSaveButton = new javax.swing.JButton();
        jExportButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(550, 500));
        setPreferredSize(new java.awt.Dimension(550, 500));
        setLayout(new java.awt.BorderLayout());

        jButtonPanel.setLayout(new java.awt.GridLayout(1, 2, 2, 5));

        jSaveButton.setText("Save");
        jSaveButton.setActionCommand("Save");
        jSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButtonActionPerformed(evt);
            }
        });
        jButtonPanel.add(jSaveButton);

        jExportButton.setText("Export");
        jExportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExportButtonActionPerformed(evt);
            }
        });
        jButtonPanel.add(jExportButton);

        add(jButtonPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButtonActionPerformed
        // tk use to test setting label data
        System.out.println("Impl saving label from SVG Label Panel");
    }//GEN-LAST:event_jSaveButtonActionPerformed

    private void jExportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExportButtonActionPerformed
        System.out.println("Impl exporting label from SVG Label Panel");
    }//GEN-LAST:event_jExportButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jButtonPanel;
    private javax.swing.JButton jExportButton;
    private javax.swing.JButton jSaveButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics pg, PageFormat pageFormat,
            int pageIndex) throws PrinterException {

        if (pageIndex >= m_maxNumPage) {
            return NO_SUCH_PAGE;
        }

        pg.translate((int) pageFormat.getImageableX(),
                (int) pageFormat.getImageableY());

        // not used
        int wPage = (int) pageFormat.getImageableWidth();
        int hPage = (int) pageFormat.getImageableHeight();

        //printContentOfLabel((Graphics2D) pg, imageScaleX, imageScaleY, 0, 0);
        System.gc();

        return PAGE_EXISTS;
    }

}
