#LabelPrint System Options
#Mon Sep 03 16:00:32 EST 2018
ConnectToDatabase=true
FontsDirectory=c\:\\windows\\fonts
PersistenceManagerFactoryClass=com.triactive.jdo.PersistenceManagerFactoryImpl
ExportGIF=false
DatabaseTable=tblProducts
LabelLogoFile=/images/BSJLogoPNG.png
ExportPDF=false
ExportJPEG=true
ConnectionDriverName=com.mysql.jdbc.Driver
HeadingImage=/images/EnergyLabelHeading.gif
ConnectionURL=jdbc\:mysql\://172.16.0.10\:3306/test
ConnectionPassword=bsj0001
DefaultFieldToSearch=Model
MostRecentSearchString=H
ExportPNG=false
Standard=178
DefaultFieldToDisplay=Model
ConnectionUserName=root
