#LabelPrint System Options
#Mon Mar 26 14:45:30 GMT-08:00 2007
ConnectionPassword=bsj0001
PersistenceManagerFactoryClass=com.triactive.jdo.PersistenceManagerFactoryImpl
LabelLogoFile=images\\BSJLogo.gif
DatabaseTable=tblProducts
DefaultFieldToSearch=Model
MostRecentSearchString=H
DefaultFieldToDisplay=Model
ConnectionURL=jdbc\:mysql\://172.16.0.10:3306/test
ConnectionDriverName=com.mysql.jdbc.Driver
ConnectionUserName=root
ExportJPEG=true
ExportGIF=false
ExportPNG=false
ExportPDF=false
FontsDirectory=c:\\windows\\fonts
HeadingImage=images\\EnergyLabelHeading.gif
Standard=178
ConnectToDatabase=true
